[tool.isort]
profile = "black"

[tool.djlint]
blank_line_after_tag = "load,extends"
close_void_tags = true
format_css = true
format_js = true
# TODO: remove T002 when fixed https://github.com/djlint/djLint/issues/687
ignore = "H006,H030,H031,T002"
include = "H017,H035"
indent = 2
max_line_length = 120
line_break_after_multiline_tag=true

profile = "django"

[tool.djlint.js]
indent_size=2
