# Generated by Django 5.0.6 on 2024-06-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scores",
                to="scoring.player",
            ),
        ),
        migrations.CreateModel(
            name="OTPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ot_players",
                        to="scoring.table",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="score",
            name="ot_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scoring.otplayer",
            ),
        ),
        migrations.AddConstraint(
            model_name="otplayer",
            constraint=models.UniqueConstraint(
                fields=("name", "table"), name="unique_ot_player_name_per_table"
            ),
        ),
    ]
