# Generated by Django 5.0.6 on 2024-06-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="complexity",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="max_players",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="max_playtime",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="min_players",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="min_playtime",
            field=models.IntegerField(null=True),
        ),
    ]
