# Generated by Django 5.0.6 on 2024-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0002_alter_score_player_otplayer_score_ot_player_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("ot_player", "scoring_category", "table"),
                name="unique_ot_player_scoring_category_table",
            ),
        ),
    ]
