# Generated by Django 5.0.6 on 2024-06-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0002_alter_game_complexity_alter_game_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoringcategory",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
