# Generated by Django 5.0.6 on 2024-06-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0003_score_unique_ot_player_scoring_category_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="table",
            name="winner",
        ),
        migrations.AddField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=10,
            ),
        ),
    ]
