# Generated by Django 5.0.6 on 2024-06-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0004_remove_table_duration_remove_table_winner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="ot_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scores",
                to="scoring.otplayer",
            ),
        ),
    ]
