# Generated by Django 5.0.6 on 2024-06-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0009_alter_table_owner_alter_table_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="favorite_games",
            field=models.ManyToManyField(to="scoring.game"),
        ),
    ]
