# Generated by Django 5.0.6 on 2024-06-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0011_alter_game_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoringcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
