# Generated by Django 5.0.6 on 2024-06-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0012_alter_scoringcategory_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scoringcategory",
            constraint=models.UniqueConstraint(
                fields=("name", "game"), name="unique_scoring_category_name_per_game"
            ),
        ),
    ]
