# Generated by Django 5.0.6 on 2024-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0013_scoringcategory_unique_scoring_category_name_per_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoringcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
