# Generated by Django 5.0.6 on 2024-06-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0014_alter_scoringcategory_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("player", "scoring_category", "table"),
                name="unique_player_scoring_category_table",
            ),
        ),
    ]
