# Generated by Django 5.0.6 on 2024-06-08 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0015_score_unique_player_scoring_category_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(related_name="games", to="scoring.genre"),
        ),
        migrations.AlterField(
            model_name="score",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scores",
                to="scoring.player",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="scoring_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scores",
                to="scoring.scoringcategory",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="scoring.table",
            ),
        ),
        migrations.AlterField(
            model_name="scoringcategory",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_categories",
                to="scoring.game",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="scoring.game",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="players",
            field=models.ManyToManyField(related_name="tables", to="scoring.player"),
        ),
        migrations.AlterField(
            model_name="table",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tables_won",
                to="scoring.player",
            ),
        ),
    ]
